//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Windows.Forms;
using System.Xml.Serialization;

namespace Cselian.IViewer
{
	public partial class AppSettings
	{
		public static readonly AppSettings Instance = new AppSettings();

		[XmlIgnore]
		public string[] KnownFolders
		{
			get { return string.IsNullOrEmpty(FavoriteFolders) ? new string[] { } : FavoriteFolders.Split('|'); }
			set { FavoriteFolders = string.Join("|", value); }
		}

		#region Properties

		public Orientation FolOrientation { get; set; }

		public int FolHorzDistance { get; set; }

		public int FolVertDistance { get; set; }

		public Orientation PlsOrientation { get; set; }

		public int PlsHorzDistance { get; set; }

		public int PlsVertDistance { get; set; }

		public SelectorType SelectorType { get; set; }

		public string FavoriteFolders { get; set; }

		public string LVWDateTimeFormat { get; set; }

		public int FilColWidthName { get; set; }

		public int FilColWidthExt { get; set; }

		public int FilColWidthSize { get; set; }

		public int FilColWidthModified { get; set; }

		public int FilColWidthFolder { get; set; }

		public bool FolVisibility { get; set; }

		#endregion
	}
}
